name = "infflow-map"
compatibility_date = "2024-01-01"
main = "src/index.ts"

[env.production]
name = "infflow-map"

[env.staging]
name = "infflow-map-staging"

# Static assets configuration
[[assets]]
directory = "dist"
binding = "ASSETS"

# Environment variables
[vars]
ENVIRONMENT = "production"
