name = "pitext-travel-backend"
compatibility_date = "2024-01-01"
main = "src/index.ts"

[env.production]
name = "pitext-travel-backend"

[env.staging]
name = "pitext-travel-backend-staging"

# Environment variables
[vars]
ENVIRONMENT = "production"

# Secrets (set via wrangler secret put)
# OPENAI_API_KEY
# GOOGLE_MAPS_API_KEY
