name = "infflow-map-voice"
compatibility_date = "2024-01-01"
main = "src/index.ts"

[env.production]
name = "infflow-map-voice"

[env.staging]
name = "infflow-map-voice-staging"

# Durable Objects
[[durable_objects.bindings]]
name = "VOICE_SESSION"
class_name = "VoiceSession"

# Environment variables
[vars]
ENVIRONMENT = "production"

# Secrets (set via wrangler secret put)
# OPENAI_API_KEY
